# -*- mode: ruby -*-
# vi: set ft=ruby :

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
BOX_IMAGE = "generic/centos8"
NODE_COUNT = 0

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox"
    #config.vm.provider "vmware_desktop"
    config.vm.provider "hyperv"
    #config.vm.box = "hashicorp/bionic64"
    config.vm.define "c8master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "c8master"
    #subconfig.vm.network :private_network, ip: "10.1.1.10"
    subconfig.vm.network "private_network", ip: "10.1.1.20"
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "c8node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "c8node#{i}"
      #subconfig.vm.network :private_network, ip: "10.1.1.#{i + 10}"
      subconfig.vm.network "private_network", ip: "10.1.1.#{i + 20}"
    end
  end

  # Install avahi on all machines  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "server-lite.yml"
  end
end
