---

- name: Copy application
  copy:
    src: "{{ application }}"
    dest: "{{ installPath }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Unarchive 
  unarchive:
    src: "{{ tarpath }}"
    dest: "{{ installPath }}"