---
- name: create install dir
  file:
    path: "{{ installPath }}"
    state: directory
    owner: root
    group: root

- name: create install dir
  file:
    path: "{{ VarLog }}"
    state: directory
    owner: "{{ user}}"
    group: "{{ user}}"


- name: Copy application
  copy:
    src: "{{ application }}"
    dest: "{{ installPath }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Unarchive 
  unarchive:
    src: "{{ tarpath }}"
    dest: "{{ installPath }}"
    remote_src: yes