---
- name: place init script
  copy:
    src: files/confluence
    dest: /etc/init.d/confluence
    owner: root
    group: root
    mode: u=x

- name: enable and start service
  service:
    name:  "{{ service }}"
    state: started
    enabled: yes

- name: start service 
  service:
    name: "{{ service }}"
    state: started
