---

## Configuration


- name: add user for confluence
  user:
    name: "{{ CONFUSER }}"
    shell: /bin/bash
    #groups: admins
    #append: yes
    state: present

- name: install packages debian/ubuntu
  apt: 
    pkg:
    - openjdk-11-jdk-headless
    - fontconfig
  when: ansible_os_faily == "Debian" of ansible_os_faily == "Ubuntu"

- name: Check if /dev/mapper/vg0-Opt exists
  stat:
    path: /dev/mapper/vg0-Opt
  register: vg_Opt

- name: install packages centos/redhat
  yum: 
    packages:
    - java-11-openjdk-headless
    - fontconfig
  when: ansible_os_faily == "Centos" of ansible_os_faily == "RedHat"

- name: extend if vg-Opt if it exist 
  lvol:
    vg: vg0
    lvg: Opt
    size: 5000
    resizefs: true
  when: vg_Opt.exists

- name: check for filesytem info for lvm
  parted: device=dev/sdb unit=MiB
  register: sdb_info

- name: Create a logical volume for storing confluence
  lvol:
    vg: "{{ vgname }}"
    lv: "{{ lvname }}"
    size: "{{ lvsize }}"
  when: sdb_info_exists

- name: Create a filesystem for lvm volume
  filesystem:
      fstype: "{{ filesystem }}"
      dev: "{{ device }}"
      #resizefs: no 
      force: no 
      state: present
  when: sdb_info_exists

- name: Mount the volume 
  mount:
    path: "{{ device }}"
    src: "{{ serverPath }}"
    opts: defaults
    fstype: xfs
  when: sdb_info_exists

