---
 - name: Install packages 
   package:
     name:
      #- cockpit
       - python3-pip
       - ansible
       - git
       - vim
     state: present
   when: ansible_facts == "Ubuntu"
  #ignore_errors: yes
  #
 - name: Install packages
   package:
     name:
      #- cockpit
       - python3-pip
       - centos-release-ansible-29
       - git
       - vim
     state: present
   when: ansible_facts == "CentOS"
  #ignore_errors: yes
 
 - name: install dep
   package:
     name: "{{ extern_dep_ubuntu }}"
     state: present
   when: ansible_facts == "Ubuntu"

 - name: install package 
   package:
     name: "{{ extern_package_ubuntu }}"
     state: present
   when: ansible_facts == "Ubuntu"


 - name: install dep
   package:
     name: "{{ extern_dep_centos }}"
     state: present
   when: ansible_facts == "CentOS"

 - name: install package 
   package:
     name: "{{ extern_package_centos }}"
     state: present
   when: ansible_facts == "CentOS"
