---

- name: install packages debian/ubuntu
  apt: 
    pkg:
    - openjdk-11-jdk-headless
    - fontconfig
  when: ansible_pkg_mgr == "apt"

- name: Check if /dev/mapper/vg0-Opt exists
  stat:
    path: /dev/mapper/vg0-Opt
  register: vg_Opt

- name: install packages centos/redhat
  yum: 
    packages:
    - java-11-openjdk-headless
    - fontconfig
  when: ansible_pkg_mgr == "yum"

